"""Tests for solver.wave_executor — parser, CLI, and round-trip contract."""
from __future__ import annotations

import json
import subprocess
from pathlib import Path
from textwrap import dedent

import pytest

from solver.validation import ScheduleInputError
from solver.wave_executor import (
    AgentSpec,
    ExecutionPlan,
    TaskSpec,
    Wave,
    _emit_json,
    _emit_shell,
    _emit_table,
    main,
    parse_schedule_md,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
EXAMPLE_SCHEDULE = REPO_ROOT / "docs" / "example-schedule.md"

# ── Fixtures ──────────────────────────────────────────────────────────────────


@pytest.fixture
def minimal_md(tmp_path: Path) -> Path:
    """Minimal valid schedule.md with 2 waves and 2 agents."""
    content = dedent("""\
        # Schedule — Test Feature

        > Generated by `/speckit.schedule` — CP-SAT Multi-Agent Optimizer
        > Status: **OPTIMAL** | Makespan: **10** time units | Waves: **2** | Agents: **2**

        ---

        ## Agent Assignments

        ### backend (claude-sonnet) — 1 tasks, 3,500 tokens (50.0% budget, 50.0% κ)

        - **T001** [Setup] t=0→5 | `src/a.py`

        ### tester (claude-haiku) — 1 tasks, 1,500 tokens (25.0% budget, 25.0% κ)

        - **T002** [Setup] t=5→10 | `tests/a.test.ts`

        ---

        ## Execution Waves

        ### Wave 1 (t=0) — Setup

        | Task | Agent | Duration | Files | Phase |
        |------|-------|----------|-------|-------|
        | T001 | backend | 5 | `src/a.py` | Setup |

        ### Wave 2 (t=5) — Setup

        | Task | Agent | Duration | Files | Phase |
        |------|-------|----------|-------|-------|
        | T002 | tester | 5 | `tests/a.test.ts` | Setup |

        ---
    """)
    md = tmp_path / "schedule.md"
    md.write_text(content, encoding="utf-8")
    return md


@pytest.fixture
def plan(minimal_md: Path) -> ExecutionPlan:
    return parse_schedule_md(minimal_md)


# ── Parser — happy path ───────────────────────────────────────────────────────


class TestParseScheduleMd:
    def test_feature_name(self, plan: ExecutionPlan):
        assert plan.feature_name == "Test Feature"

    def test_makespan(self, plan: ExecutionPlan):
        assert plan.makespan == 10

    def test_wave_count(self, plan: ExecutionPlan):
        assert len(plan.waves) == 2

    def test_wave_indices(self, plan: ExecutionPlan):
        assert plan.waves[0].index == 1
        assert plan.waves[1].index == 2

    def test_wave_start_times(self, plan: ExecutionPlan):
        assert plan.waves[0].start_time == 0
        assert plan.waves[1].start_time == 5

    def test_task_in_wave1(self, plan: ExecutionPlan):
        t = plan.waves[0].tasks[0]
        assert t.task_id == "T001"
        assert t.agent_id == "backend"
        assert t.duration == 5
        assert t.start == 0
        assert t.end == 5
        assert t.files == ("src/a.py",)
        assert t.phase == "Setup"

    def test_task_in_wave2(self, plan: ExecutionPlan):
        t = plan.waves[1].tasks[0]
        assert t.task_id == "T002"
        assert t.agent_id == "tester"
        assert t.start == 5
        assert t.end == 10

    def test_agents_parsed(self, plan: ExecutionPlan):
        assert len(plan.agents) == 2
        ids = {a.id for a in plan.agents}
        assert ids == {"backend", "tester"}

    def test_agent_model(self, plan: ExecutionPlan):
        backend = next(a for a in plan.agents if a.id == "backend")
        assert backend.model == "claude-sonnet"

    def test_agent_no_provider(self, plan: ExecutionPlan):
        backend = next(a for a in plan.agents if a.id == "backend")
        assert backend.provider is None

    def test_returns_frozen_plan(self, plan: ExecutionPlan):
        with pytest.raises((AttributeError, TypeError)):
            plan.feature_name = "mutated"  # type: ignore[misc]

    def test_accepts_path_object(self, minimal_md: Path):
        p = parse_schedule_md(minimal_md)
        assert isinstance(p, ExecutionPlan)

    def test_accepts_string_path(self, minimal_md: Path):
        p = parse_schedule_md(str(minimal_md))
        assert isinstance(p, ExecutionPlan)


class TestParseAgentWithProvider:
    def test_provider_parsed(self, tmp_path: Path):
        content = dedent("""\
            # Schedule — F

            > Status: **OPTIMAL** | Makespan: **5** time units | Waves: **1** | Agents: **1**

            ## Agent Assignments

            ### backend (claude-sonnet · anthropic) — 1 tasks, 3,500 tokens (50.0% budget, 50.0% κ)

            - **T001** [Setup] t=0→5 | `src/a.py`

            ## Execution Waves

            ### Wave 1 (t=0) — Setup

            | Task | Agent | Duration | Files | Phase |
            |------|-------|----------|-------|-------|
            | T001 | backend | 5 | `src/a.py` | Setup |
        """)
        md = tmp_path / "s.md"
        md.write_text(content, encoding="utf-8")
        plan = parse_schedule_md(md)
        a = plan.agents[0]
        assert a.model == "claude-sonnet"
        assert a.provider == "anthropic"


class TestParseNoFilesColumn:
    def test_missing_files_column(self, tmp_path: Path):
        """Parser should not crash when the Files column is absent."""
        content = dedent("""\
            # Schedule — F

            > Status: **OPTIMAL** | Makespan: **5** time units | Waves: **1** | Agents: **1**

            ## Agent Assignments

            ### backend (test-model) — 1 tasks, 0 tokens (0.0% budget, 0.0% κ)

            ## Execution Waves

            ### Wave 1 (t=0) — Setup

            | Task | Agent | Duration | Phase |
            |------|-------|----------|-------|
            | T001 | backend | 5 | Setup |
        """)
        md = tmp_path / "s.md"
        md.write_text(content, encoding="utf-8")
        plan = parse_schedule_md(md)
        assert plan.waves[0].tasks[0].files == ()


class TestParseRobustness:
    def test_em_dash_in_heading(self, tmp_path: Path):
        content = dedent("""\
            # Schedule — Em Dash Feature

            > Status: **OPTIMAL** | Makespan: **5** time units | Waves: **1** | Agents: **1**

            ## Agent Assignments

            ### backend (m) — 1 tasks, 0 tokens (0% budget, 0% κ)

            ## Execution Waves

            ### Wave 1 (t=0) — Setup

            | Task | Agent | Duration | Files | Phase |
            |------|-------|----------|-------|-------|
            | T001 | backend | 5 | | Setup |
        """)
        md = tmp_path / "s.md"
        md.write_text(content, encoding="utf-8")
        plan = parse_schedule_md(md)
        assert plan.feature_name == "Em Dash Feature"
        assert plan.waves[0].index == 1

    def test_extra_blank_lines_tolerated(self, tmp_path: Path):
        content = dedent("""\
            # Schedule — Spacy



            > Status: **OPTIMAL** | Makespan: **5** time units | Waves: **1** | Agents: **1**



            ## Agent Assignments

            ### backend (m) — 1 tasks, 0 tokens (0% budget, 0% κ)

            ## Execution Waves


            ### Wave 1 (t=0) — Setup


            | Task | Agent | Duration | Files | Phase |
            |------|-------|----------|-------|-------|

            | T001 | backend | 5 | | Setup |


        """)
        md = tmp_path / "s.md"
        md.write_text(content, encoding="utf-8")
        plan = parse_schedule_md(md)
        assert plan.feature_name == "Spacy"


# ── Parser — error handling ───────────────────────────────────────────────────


class TestParseErrors:
    def test_missing_file(self, tmp_path: Path):
        with pytest.raises(ScheduleInputError, match="Cannot read"):
            parse_schedule_md(tmp_path / "nonexistent.md")

    def test_no_heading(self, tmp_path: Path):
        md = tmp_path / "s.md"
        md.write_text("Nothing useful here.\n", encoding="utf-8")
        with pytest.raises(ScheduleInputError, match="No '# Schedule"):
            parse_schedule_md(md)

    def test_no_metadata_line(self, tmp_path: Path):
        md = tmp_path / "s.md"
        md.write_text("# Schedule — F\n\nNo metadata.\n", encoding="utf-8")
        with pytest.raises(ScheduleInputError, match="No status metadata"):
            parse_schedule_md(md)

    def test_no_waves(self, tmp_path: Path):
        md = tmp_path / "s.md"
        md.write_text(
            "# Schedule — F\n\n"
            "> Status: **OPTIMAL** | Makespan: **5** time units | Waves: **0** | Agents: **1**\n\n"
            "## Agent Assignments\n\n### backend (m) — 0 tasks\n",
            encoding="utf-8",
        )
        with pytest.raises(ScheduleInputError, match="No wave sections"):
            parse_schedule_md(md)

    def test_wave_count_mismatch(self, tmp_path: Path):
        content = dedent("""\
            # Schedule — F

            > Status: **OPTIMAL** | Makespan: **5** time units | Waves: **3** | Agents: **1**

            ## Agent Assignments

            ### backend (m) — 1 tasks, 0 tokens (0% budget, 0% κ)

            ## Execution Waves

            ### Wave 1 (t=0) — Setup

            | Task | Agent | Duration | Files | Phase |
            |------|-------|----------|-------|-------|
            | T001 | backend | 5 | | Setup |
        """)
        md = tmp_path / "s.md"
        md.write_text(content, encoding="utf-8")
        with pytest.raises(ScheduleInputError, match="Metadata declares 3 waves but 1"):
            parse_schedule_md(md)

    def test_no_agents(self, tmp_path: Path):
        content = dedent("""\
            # Schedule — F

            > Status: **OPTIMAL** | Makespan: **5** time units | Waves: **1** | Agents: **1**

            ## Execution Waves

            ### Wave 1 (t=0) — Setup

            | Task | Agent | Duration | Files | Phase |
            |------|-------|----------|-------|-------|
            | T001 | backend | 5 | | Setup |
        """)
        md = tmp_path / "s.md"
        md.write_text(content, encoding="utf-8")
        with pytest.raises(ScheduleInputError, match="No agent headings"):
            parse_schedule_md(md)

    def test_orphan_agent_in_wave(self, tmp_path: Path):
        content = dedent("""\
            # Schedule — F

            > Status: **OPTIMAL** | Makespan: **5** time units | Waves: **1** | Agents: **1**

            ## Agent Assignments

            ### backend (m) — 1 tasks, 0 tokens (0% budget, 0% κ)

            ## Execution Waves

            ### Wave 1 (t=0) — Setup

            | Task | Agent | Duration | Files | Phase |
            |------|-------|----------|-------|-------|
            | T001 | ghost-agent | 5 | | Setup |
        """)
        md = tmp_path / "s.md"
        md.write_text(content, encoding="utf-8")
        with pytest.raises(ScheduleInputError, match="unknown agent"):
            parse_schedule_md(md)


# ── Emitters ─────────────────────────────────────────────────────────────────

def _make_plan() -> ExecutionPlan:
    return ExecutionPlan(
        feature_name="Test",
        makespan=10,
        waves=(
            Wave(
                index=1,
                start_time=0,
                tasks=(
                    TaskSpec(
                        task_id="T001", agent_id="backend",
                        start=0, end=5, duration=5,
                        files=("src/a.py",), phase="Setup",
                    ),
                ),
            ),
            Wave(
                index=2,
                start_time=5,
                tasks=(
                    TaskSpec(
                        task_id="T002", agent_id="tester",
                        start=5, end=10, duration=5,
                        files=("tests/a.test.ts",), phase="Setup",
                    ),
                ),
            ),
        ),
        agents=(
            AgentSpec(id="backend", model="claude-sonnet", provider=None),
            AgentSpec(id="tester", model="claude-haiku", provider=None),
        ),
        metadata={},
    )


class TestEmitJson:
    def test_json_structure(self):
        out = _emit_json(_make_plan())
        d = json.loads(out)
        assert d["feature_name"] == "Test"
        assert d["makespan"] == 10
        assert len(d["waves"]) == 2
        assert len(d["agents"]) == 2

    def test_wave_tasks_serialised(self):
        d = json.loads(_emit_json(_make_plan()))
        t = d["waves"][0]["tasks"][0]
        assert t["task_id"] == "T001"
        assert t["agent_id"] == "backend"
        assert t["duration"] == 5
        assert t["files"] == ["src/a.py"]

    def test_agents_serialised(self):
        d = json.loads(_emit_json(_make_plan()))
        agents = {a["id"]: a for a in d["agents"]}
        assert agents["backend"]["model"] == "claude-sonnet"
        assert agents["backend"]["provider"] is None


class TestEmitShell:
    def test_shebang(self):
        out = _emit_shell(_make_plan())
        assert out.startswith("#!/usr/bin/env sh")

    def test_set_euo_pipefail(self):
        out = _emit_shell(_make_plan())
        assert "set -euo pipefail" in out

    def test_runner_check(self):
        out = _emit_shell(_make_plan())
        assert "RUNNER" in out

    def test_wait_between_waves(self):
        out = _emit_shell(_make_plan())
        lines = out.splitlines()
        # Each wave block must have a "wait" after agent launches.
        wait_count = sum(1 for line in lines if line.strip() == "wait")
        assert wait_count == 2  # one per wave

    def test_agent_launched_in_background(self):
        out = _emit_shell(_make_plan())
        assert "$RUNNER backend T001 &" in out
        assert "$RUNNER tester T002 &" in out

    def test_valid_posix_syntax(self, tmp_path: Path):
        out = _emit_shell(_make_plan())
        script = tmp_path / "plan.sh"
        script.write_text(out, encoding="utf-8")
        result = subprocess.run(
            ["bash", "-n", str(script)], capture_output=True
        )
        assert result.returncode == 0, result.stderr.decode()


class TestEmitTable:
    def test_contains_header(self):
        out = _emit_table(_make_plan())
        assert "Wave" in out
        assert "Agent" in out
        assert "Task" in out
        assert "Files" in out

    def test_contains_task_data(self):
        out = _emit_table(_make_plan())
        assert "T001" in out
        assert "backend" in out

    def test_aligned_columns(self):
        out = _emit_table(_make_plan())
        lines = out.splitlines()
        # Header and separator must exist.
        assert len(lines) >= 3


# ── CLI ───────────────────────────────────────────────────────────────────────


class TestCLI:
    def test_json_format(self, minimal_md: Path):
        rc = main([str(minimal_md), "--format", "json"])
        assert rc == 0

    def test_shell_format(self, minimal_md: Path, capsys):
        rc = main([str(minimal_md), "--format", "shell"])
        assert rc == 0
        out = capsys.readouterr().out
        assert "set -euo pipefail" in out

    def test_table_format(self, minimal_md: Path, capsys):
        rc = main([str(minimal_md), "--format", "table"])
        assert rc == 0
        out = capsys.readouterr().out
        assert "Wave" in out

    def test_default_format_is_json(self, minimal_md: Path, capsys):
        rc = main([str(minimal_md)])
        assert rc == 0
        out = capsys.readouterr().out
        json.loads(out)  # must be valid JSON

    def test_missing_file_returns_2(self, tmp_path: Path, capsys):
        rc = main([str(tmp_path / "missing.md")])
        assert rc == 2

    def test_bad_format_raises_system_exit(self, minimal_md: Path):
        with pytest.raises(SystemExit):
            main([str(minimal_md), "--format", "xml"])


# ── Round-trip: example-schedule.md ──────────────────────────────────────────


@pytest.mark.skipif(
    not EXAMPLE_SCHEDULE.exists(),
    reason="docs/example-schedule.md not present",
)
class TestExampleRoundTrip:
    def test_parses_without_error(self):
        plan = parse_schedule_md(EXAMPLE_SCHEDULE)
        assert isinstance(plan, ExecutionPlan)

    def test_feature_name(self):
        plan = parse_schedule_md(EXAMPLE_SCHEDULE)
        assert plan.feature_name == "Create Taskify"

    def test_makespan(self):
        plan = parse_schedule_md(EXAMPLE_SCHEDULE)
        assert plan.makespan == 315

    def test_wave_count(self):
        plan = parse_schedule_md(EXAMPLE_SCHEDULE)
        assert len(plan.waves) > 0

    def test_agent_count(self):
        plan = parse_schedule_md(EXAMPLE_SCHEDULE)
        assert len(plan.agents) == 5

    def test_all_tasks_present(self):
        plan = parse_schedule_md(EXAMPLE_SCHEDULE)
        all_task_ids = {t.task_id for w in plan.waves for t in w.tasks}
        # example has T001-T028
        assert len(all_task_ids) == 28

    def test_json_roundtrip(self):
        plan = parse_schedule_md(EXAMPLE_SCHEDULE)
        d = json.loads(_emit_json(plan))
        assert d["makespan"] == plan.makespan
        assert len(d["waves"]) == len(plan.waves)

    def test_shell_syntax(self, tmp_path: Path):
        plan = parse_schedule_md(EXAMPLE_SCHEDULE)
        script = tmp_path / "plan.sh"
        script.write_text(_emit_shell(plan), encoding="utf-8")
        result = subprocess.run(
            ["bash", "-n", str(script)], capture_output=True
        )
        assert result.returncode == 0, result.stderr.decode()

    def test_table_has_all_tasks(self):
        plan = parse_schedule_md(EXAMPLE_SCHEDULE)
        table = _emit_table(plan)
        for wave in plan.waves:
            for task in wave.tasks:
                assert task.task_id in table

    def test_cli_json_output(self, capsys):
        rc = main([str(EXAMPLE_SCHEDULE), "--format", "json"])
        assert rc == 0
        out = capsys.readouterr().out
        d = json.loads(out)
        plan = parse_schedule_md(EXAMPLE_SCHEDULE)
        assert d["makespan"] == 315
        assert len(d["waves"]) == len(plan.waves)

    def test_task_start_end_consistency(self):
        """start + duration == end for every parsed task."""
        plan = parse_schedule_md(EXAMPLE_SCHEDULE)
        for wave in plan.waves:
            for task in wave.tasks:
                assert task.start + task.duration == task.end, (
                    f"{task.task_id}: {task.start} + {task.duration} != {task.end}"
                )
