#!/usr/bin/env python3
"""spec-kit-schedule: schedule.md Renderer.

Reads solver JSON output and produces a formatted schedule.md with agent
assignments, execution waves, Gantt chart, DAG, solver statistics, and any
warnings the solver surfaced.

Usage:
    python render_schedule.py <solver_output.json> <feature_name> > schedule.md
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from collections import defaultdict
from itertools import pairwise
from typing import Any

if __package__ in (None, ""):
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    __package__ = "solver"  # noqa: A001

from ._render_helpers import format_agent_model_label, task_label
from .defaults import AGENT_COLORS, CRITICAL_COLOR
from .model.result_types import ScheduleResult  # noqa: F401  (schema doc — see render() docstring)

__all__ = ["render", "main"]


def _mermaid_id(agent_id: str) -> str:
    return agent_id.replace("-", "_").replace(".", "_")


def render(
    data: dict[str, Any],
    feature_name: str,
    *,
    image_prefix: str | None = None,
) -> str:
    """Render solver output as schedule.md markdown.

    The expected shape is :class:`solver.model.result_types.ScheduleResult`;
    raw ``dict[str, Any]`` stays as the runtime annotation so legacy
    callers don't have to import the TypedDict.

    If `image_prefix` is given, insert `![](…-dag.png)` / `…-gantt.png`
    references so consumers that cannot render Mermaid (printed reports,
    slide decks, some IDEs) still see the charts. Callers typically pass
    e.g. `images/my-feature` after running `python -m solver.visualize`,
    which produces ``{prefix}-dag.{ext}`` and ``{prefix}-gantt.{ext}``.

    Note: the HTML renderer (``solver.render_html``) deliberately omits
    this knob — its output is a self-contained Plotly document, so
    embedding pre-rendered PNGs would be redundant. Markdown can only
    reference external images, hence the asymmetry.
    """
    stats = data.get("stats", {})
    assignments = data.get("assignments", [])
    waves = data.get("waves", [])
    agent_summary = data.get("agent_summary", [])
    parser_edges = data.get("edges", [])
    resource_edges = data.get("resource_edges", [])
    warnings = data.get("warnings", [])
    critical_path: list[str] = data.get("critical_path", [])
    critical_set = set(critical_path)
    # Prefer the solver-supplied critical-path arcs (which include induced
    # resource edges); fall back to `pairwise(critical_path)` for older
    # solver outputs that predate the field.
    critical_edges = {
        (src, dst) for src, dst in data.get("critical_path_edges", list(pairwise(critical_path)))
    }

    lines: list[str] = []

    # ── Header ────────────────────────────────────────────────────────
    lines.append(f"# Schedule — {feature_name}")
    lines.append("")
    lines.append("> Generated by `/speckit.schedule` — CP-SAT Multi-Agent Optimizer")
    lines.append(
        f"> Status: **{stats.get('status', 'UNKNOWN')}** | "
        f"Makespan: **{stats.get('makespan', '?')}** time units | "
        f"Waves: **{stats.get('total_waves', '?')}** | "
        f"Agents: **{stats.get('total_agents', '?')}**"
    )
    lines.append("")
    lines.append("---")
    lines.append("")

    if warnings:
        lines.append("## ⚠ Warnings")
        lines.append("")
        for w in warnings:
            code = w.get("code", "warning")
            msg = w.get("message", "")
            lines.append(f"- **[{code}]** {msg}")
            ctx = w.get("context") or {}
            if ctx:
                rendered = ", ".join(f"`{k}`={v!r}" for k, v in ctx.items())
                lines.append(f"  - context: {rendered}")
        lines.append("")
        lines.append("---")
        lines.append("")

    # ── Agent Assignments ─────────────────────────────────────────────
    lines.append("## Agent Assignments")
    lines.append("")
    for ag in agent_summary:
        budget_pct = ag.get("budget_utilization", 0)
        kappa_pct = ag.get("kappa_utilization", 0)
        model_label = format_agent_model_label(ag)
        lines.append(
            f"### {ag['agent_id']} ({model_label}) — "
            f"{ag['task_count']} tasks, "
            f"{ag['total_tokens']:,} tokens "
            f"({budget_pct}% budget, {kappa_pct}% κ)"
        )
        lines.append("")
        agent_tasks = [a for a in assignments if a["agent_id"] == ag["agent_id"]]
        agent_tasks.sort(key=lambda t: t["start"])
        for t in agent_tasks:
            files = ", ".join(f"`{f}`" for f in t.get("file_paths", []))
            label = task_label(t)
            lines.append(f"- **{t['task_id']}** [{label}] t={t['start']}→{t['end']} | {files}")
        lines.append("")

    lines.append("---")
    lines.append("")

    # ── Execution Waves ───────────────────────────────────────────────
    lines.append("## Execution Waves")
    lines.append("")
    for wave in waves:
        wave_tasks = wave["tasks"]
        phase_label = " + ".join(sorted({t["phase"] for t in wave_tasks}))
        lines.append(f"### Wave {wave['wave']} (t={wave['start_time']}) — {phase_label}")
        lines.append("")
        lines.append("| Task | Agent | Duration | Files | Phase |")
        lines.append("|------|-------|----------|-------|-------|")
        for t in wave_tasks:
            files = ", ".join(f"`{f}`" for f in t.get("file_paths", []))
            label = task_label(t)
            lines.append(
                f"| {t['task_id']} | {t['agent_id']} | {t['duration']} | " f"{files} | {label} |"
            )
        lines.append("")

    lines.append("---")
    lines.append("")

    # ── Critical Path ─────────────────────────────────────────────────
    if critical_path:
        by_id = {a["task_id"]: a for a in assignments}
        lines.append("## Critical Path")
        lines.append("")
        lines.append(
            "Tasks on this chain dictate the makespan — slipping any of "
            "them extends the whole schedule by the same amount. Reducing "
            "their duration (splitting, parallelising, or assigning to a "
            "faster agent) is the only way to shorten the project."
        )
        lines.append("")
        lines.append("| # | Task | Agent | Start | End | Duration | Cumulative |")
        lines.append("|---|------|-------|-------|-----|----------|------------|")
        cumulative = 0
        for i, task_id in enumerate(critical_path, 1):
            a = by_id.get(task_id)
            if a is None:
                continue
            cumulative += a["duration"]
            lines.append(
                f"| {i} | **{task_id}** | {a['agent_id']} | "
                f"{a['start']} | {a['end']} | {a['duration']} | {cumulative} |"
            )
        lines.append("")
        lines.append("---")
        lines.append("")

    # ── Gantt ─────────────────────────────────────────────────────────
    lines.append("## Gantt Chart")
    lines.append("")
    if image_prefix:
        lines.append(f"![Gantt]({image_prefix}-gantt.png)")
        lines.append("")
    lines.append("```mermaid")
    lines.append("gantt")
    lines.append(f"    title {feature_name} — Multi-Agent Schedule")
    lines.append("    dateFormat X")
    lines.append("    axisFormat %s")
    lines.append("")

    agent_tasks_map: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for a in assignments:
        agent_tasks_map[a["agent_id"]].append(a)

    for ag_id, tasks in agent_tasks_map.items():
        tasks.sort(key=lambda t: t["start"])
        lines.append(f"    section {ag_id}")
        for t in tasks:
            tag = f"{_mermaid_id(ag_id)[:3]}{t['task_id'][1:]}"
            marker = "crit, " if t["task_id"] in critical_set else ""
            # With `dateFormat X` Mermaid reads the third column as an
            # absolute END time (Unix seconds), not a duration. Passing
            # `duration` produces bars of length 0 or negative width when
            # `duration < start`.
            lines.append(f"    {t['task_id']} :{marker}{tag}, " f"{t['start']}, {t['end']}")
        lines.append("")

    lines.append("```")
    lines.append("")
    lines.append("---")
    lines.append("")

    lines.append("## Dependency DAG")
    lines.append("")
    if image_prefix:
        lines.append(f"![DAG]({image_prefix}-dag.png)")
        lines.append("")
    lines.append("```mermaid")
    lines.append("graph LR")
    for idx, ag_id in enumerate(agent_tasks_map):
        color = AGENT_COLORS[idx % len(AGENT_COLORS)]
        lines.append(
            f"    classDef {_mermaid_id(ag_id)} " f"fill:{color},color:#fff,stroke:{color}"
        )
    if critical_set:
        lines.append(
            f"    classDef critical stroke:{CRITICAL_COLOR},stroke-width:4px,color:#fff"
        )
    lines.append("")

    drawn: set[tuple[str, str]] = set()
    # Always draw every critical arc first so they cannot be hidden by
    # missing parser edges (the chain includes resource-induced arcs).
    for src, dst in critical_edges:
        if (src, dst) in drawn:
            continue
        lines.append(f"    {src} ==> {dst}")
        drawn.add((src, dst))
    for src, dst in parser_edges:
        key = (src, dst)
        if key in drawn:
            continue
        lines.append(f"    {src} --> {dst}")
        drawn.add(key)
    for src, dst in resource_edges:
        key = (src, dst)
        if key in drawn:
            continue
        # Dotted arrow signals "induced by same-agent / file-mutex", so
        # readers can see why two tasks are sequenced without an explicit
        # `(depends on …)` edge.
        lines.append(f"    {src} -.-> {dst}")
        drawn.add(key)
    lines.append("")

    for ag_id, tasks in agent_tasks_map.items():
        ids = [t["task_id"] for t in tasks]
        if ids:
            lines.append(f"    class {','.join(ids)} {_mermaid_id(ag_id)}")
    if critical_set:
        lines.append(f"    class {','.join(sorted(critical_set))} critical")

    lines.append("```")
    lines.append("")
    lines.append("---")
    lines.append("")

    # ── Solver Statistics ─────────────────────────────────────────────
    lines.append("## Solver Statistics")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    max_load = stats.get("max_load")
    min_load = stats.get("min_load")
    load_range = (
        max_load - min_load if isinstance(max_load, int) and isinstance(min_load, int) else "?"
    )
    rows = [
        ("Total tasks", stats.get("total_tasks", "?")),
        ("Total agents", stats.get("total_agents", "?")),
        ("Makespan (C_max)", f"{stats.get('makespan', '?')} time units"),
        ("Max agent load (L_max)", f"{max_load if max_load is not None else '?'} time units"),
        ("Min agent load (L_min)", f"{min_load if min_load is not None else '?'} time units"),
        ("Load range", f"{load_range} time units"),
        ("Execution waves", stats.get("total_waves", "?")),
        ("Horizon", stats.get("horizon", "?")),
        ("Phase 1 time", f"{stats.get('phase1_time', '?')}s"),
        ("Phase 1 status", stats.get("phase1_status", "?")),
        ("Phase 2 time", f"{stats.get('phase2_time', '?')}s"),
        ("Phase 2 status", stats.get("phase2_status", "?")),
        ("Status", stats.get("status", "?")),
    ]
    for name, value in rows:
        lines.append(f"| {name} | {value} |")
    lines.append("")

    return "\n".join(lines)


def _build_argparser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(
        prog="render_schedule.py",
        description="Render solver output JSON into schedule.md.",
    )
    ap.add_argument("input", help="Path to solver output JSON")
    ap.add_argument("feature_name")
    ap.add_argument(
        "--image-prefix",
        default=None,
        help="Embed `{prefix}-dag.png` and `{prefix}-gantt.png` references "
        "in the markdown (produce them with `python -m solver.visualize`).",
    )
    return ap


def main(argv: list[str] | None = None) -> int:
    args = _build_argparser().parse_args(argv)
    with open(args.input, encoding="utf-8") as f:
        data = json.load(f)
    sys.stdout.write(
        render(data, args.feature_name, image_prefix=args.image_prefix).rstrip() + "\n"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
