"""spec-kit-schedule: Interactive HTML renderer.

Produces a fully self-contained schedule.html using Plotly for interactive
Gantt and DAG charts. No external image files required.

Usage
-----
    python -m solver.render_html out.json <feature> [--inline-plotly]
        > schedule.html
"""

from __future__ import annotations

import argparse
import html
import json
import os
import sys
from collections import defaultdict
from datetime import datetime, timezone
from itertools import pairwise
from typing import Any

if __package__ in (None, ""):
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    __package__ = "solver"  # noqa: A001

from ._render_helpers import format_agent_model_label, task_label
from .defaults import (
    AGENT_COLORS,
    CRITICAL_COLOR,
    STATUS_FEASIBLE,
    STATUS_OPTIMAL,
    STATUS_UNKNOWN,
    palette_for,
)
from .model.build import cost_dollars
from .model.result_types import ScheduleResult  # noqa: F401  (schema doc — see render() docstring)

__all__ = ["render", "main"]

# Plotly figure dimensions (Gantt chart). Centralised so the renderer
# can be tuned without hunting through the chart-builder body.
_GANTT_MIN_HEIGHT = 300
_GANTT_PER_AGENT_HEIGHT = 80
_GANTT_BAR_WIDTH = 0.55
_GANTT_MARGIN_T = 60
_GANTT_MARGIN_R = 20
_GANTT_MARGIN_B = 60
_GANTT_MARGIN_L = 120
# Extra title-area padding included in the height calculation so the
# top margin doesn't crowd a one-row Gantt.
_GANTT_TITLE_PAD = 120

_FALLBACK_COLOR = "#888888"
_RESOURCE_EDGE_COLOR = "#999999"
_PARSER_EDGE_COLOR = "#AAAAAA"
_CRITICAL_EDGE_COLOR = CRITICAL_COLOR
_CRITICAL_MARKER_PATTERN = "/"
_CRITICAL_BORDER_COLOR = CRITICAL_COLOR


def _require_plotly() -> None:
    try:
        import plotly  # noqa: F401
    except ImportError as exc:
        raise ImportError(
            "plotly is required for solver.render_html. Install with "
            "`uv sync --extra viz` or `pip install 'plotly>=5,<6'`."
        ) from exc


def _esc(text: object) -> str:
    return html.escape(str(text))


def _color_for_agent(agent_id: str, agents_sorted: list[str]) -> str:
    try:
        idx = agents_sorted.index(agent_id)
        return AGENT_COLORS[idx % len(AGENT_COLORS)]
    except ValueError:
        return _FALLBACK_COLOR


# ---------------------------------------------------------------------------
# HTML section builders (pure string; no plotly dependency)
# ---------------------------------------------------------------------------

def _header_html(data: dict[str, Any], feature_name: str) -> str:
    stats = data.get("stats", {})
    status = stats.get("status", data.get("status", STATUS_UNKNOWN))
    makespan = stats.get("makespan", "?")
    waves = stats.get("total_waves", "?")
    agents = stats.get("total_agents", "?")
    ts = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    badge_color = "#2ecc71" if STATUS_OPTIMAL in str(status) else (
        "#f39c12" if STATUS_FEASIBLE in str(status) else "#e74c3c"
    )
    return f"""
<div class="card header-card">
  <h1>Schedule &mdash; {_esc(feature_name)}</h1>
  <p>Generated by <code>/speckit.schedule</code> &mdash; CP-SAT Multi-Agent Optimizer
  &mdash; {_esc(ts)}</p>
  <div class="badges">
    <span class="badge" style="background:{_esc(badge_color)}">
      Status: {_esc(status)}
    </span>
    <span class="badge">Makespan: <strong>{_esc(makespan)}</strong></span>
    <span class="badge">Waves: <strong>{_esc(waves)}</strong></span>
    <span class="badge">Agents: <strong>{_esc(agents)}</strong></span>
  </div>
</div>
"""


def _warnings_html(data: dict[str, Any]) -> str:
    warnings = data.get("warnings", [])
    if not warnings:
        return ""
    items = []
    for w in warnings:
        code = w.get("code", "warning")
        msg = w.get("message", "")
        ctx = w.get("context") or {}
        ctx_str = ", ".join(f"{k}={v!r}" for k, v in ctx.items())
        ctx_html = f" <small>({_esc(ctx_str)})</small>" if ctx_str else ""
        items.append(
            f"<li><strong>[{_esc(code)}]</strong> {_esc(msg)}{ctx_html}</li>"
        )
    return f"""
<div class="card warnings-card">
  <h2>&#9888; Warnings</h2>
  <ul>{"".join(items)}</ul>
</div>
"""


def _agent_assignments_html(data: dict[str, Any], agents_sorted: list[str]) -> str:
    assignments = data.get("assignments", [])
    agent_summary = data.get("agent_summary", [])
    by_agent: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for a in assignments:
        by_agent[a["agent_id"]].append(a)

    summary_by_id = {s["agent_id"]: s for s in agent_summary}
    cards = []
    for agent_id in agents_sorted:
        color = _color_for_agent(agent_id, agents_sorted)
        summary = summary_by_id.get(agent_id, {})
        budget_pct = summary.get("budget_utilization", 0)
        kappa_pct = summary.get("kappa_utilization", 0)
        model_label = format_agent_model_label(summary, sep="&middot;", esc=_esc)
        task_count = summary.get("task_count", 0)
        total_tokens = summary.get("total_tokens", 0)

        task_items = []
        for t in sorted(by_agent.get(agent_id, []), key=lambda x: x["start"]):
            files = ", ".join(f"<code>{_esc(f)}</code>" for f in t.get("file_paths", []))
            label = task_label(t)
            task_items.append(
                f"<li><strong>{_esc(t['task_id'])}</strong> "
                f"[{_esc(label)}] "
                f"t={_esc(t['start'])}&rarr;{_esc(t['end'])} | {files}</li>"
            )

        cards.append(f"""
<div class="agent-card" style="border-left: 4px solid {_esc(color)}">
  <h3 style="color:{_esc(color)}">{_esc(agent_id)}</h3>
  <p>{model_label} &mdash; {_esc(task_count)} tasks,
  {_esc(f"{total_tokens:,}")} tokens
  ({_esc(budget_pct)}% budget, {_esc(kappa_pct)}% &kappa;)</p>
  <ul>{"".join(task_items)}</ul>
</div>""")

    return f"""
<div class="card">
  <h2>Agent Assignments</h2>
  <div class="agent-grid">{"".join(cards)}</div>
</div>
"""


def _waves_html(data: dict[str, Any]) -> str:
    waves = data.get("waves", [])
    if not waves:
        return ""
    items = []
    for wave in waves:
        wave_tasks = wave.get("tasks", [])
        wave_num = wave.get("wave", "?")
        start_time = wave.get("start_time", "?")
        phases = " + ".join(sorted({t.get("phase", "?") for t in wave_tasks}))
        open_attr = ' open' if wave_num == 1 else ""
        rows = []
        for t in wave_tasks:
            files = ", ".join(f"<code>{_esc(f)}</code>" for f in t.get("file_paths", []))
            label = t.get("story_id") or t.get("phase", "?")
            rows.append(
                f"<tr><td>{_esc(t['task_id'])}</td>"
                f"<td>{_esc(t.get('agent_id','?'))}</td>"
                f"<td>{_esc(t.get('duration','?'))}</td>"
                f"<td>{files}</td>"
                f"<td>{_esc(label)}</td></tr>"
            )
        items.append(f"""
<details{open_attr}>
  <summary>Wave {_esc(wave_num)} (t={_esc(start_time)}) &mdash; {_esc(phases)}</summary>
  <table>
    <thead><tr>
      <th>Task</th><th>Agent</th><th>Duration</th><th>Files</th><th>Phase</th>
    </tr></thead>
    <tbody>{"".join(rows)}</tbody>
  </table>
</details>""")

    return f"""
<div class="card">
  <h2>Execution Waves</h2>
  {"".join(items)}
</div>
"""


def _critical_path_html(data: dict[str, Any]) -> str:
    critical_path: list[str] = data.get("critical_path", [])
    if not critical_path:
        return ""
    assignments = data.get("assignments", [])
    by_id = {a["task_id"]: a for a in assignments}
    rows = []
    cumulative = 0
    for i, task_id in enumerate(critical_path, 1):
        a = by_id.get(task_id)
        if a is None:
            continue
        cumulative += a["duration"]
        rows.append(
            f"<tr><td>{i}</td>"
            f"<td><strong>{_esc(task_id)}</strong></td>"
            f"<td>{_esc(a['agent_id'])}</td>"
            f"<td>{_esc(a['start'])}</td>"
            f"<td>{_esc(a['end'])}</td>"
            f"<td>{_esc(a['duration'])}</td>"
            f"<td>{cumulative}</td></tr>"
        )
    return f"""
<div class="card">
  <h2>Critical Path</h2>
  <p>Tasks on this chain dictate the makespan. Reducing their duration
  is the only way to shorten the project.</p>
  <table>
    <thead><tr>
      <th>#</th><th>Task</th><th>Agent</th>
      <th>Start</th><th>End</th><th>Duration</th><th>Cumulative</th>
    </tr></thead>
    <tbody>{"".join(rows)}</tbody>
  </table>
</div>
"""


def _stats_html(data: dict[str, Any]) -> str:
    stats = data.get("stats", {})
    max_load = stats.get("max_load")
    min_load = stats.get("min_load")
    load_range = (
        max_load - min_load
        if isinstance(max_load, int) and isinstance(min_load, int)
        else "?"
    )
    rows_data = [
        ("Total tasks", stats.get("total_tasks", "?")),
        ("Total agents", stats.get("total_agents", "?")),
        ("Makespan (C_max)", f"{stats.get('makespan', '?')} time units"),
        ("Max agent load (L_max)", f"{max_load if max_load is not None else '?'} time units"),
        ("Min agent load (L_min)", f"{min_load if min_load is not None else '?'} time units"),
        ("Load range", f"{load_range} time units"),
        ("Execution waves", stats.get("total_waves", "?")),
        ("Horizon", stats.get("horizon", "?")),
        ("Phase 1 time", f"{stats.get('phase1_time', '?')}s"),
        ("Phase 1 status", stats.get("phase1_status", "?")),
        ("Phase 2 time", f"{stats.get('phase2_time', '?')}s"),
        ("Phase 2 status", stats.get("phase2_status", "?")),
        ("Status", stats.get("status", "?")),
    ]
    rows = "".join(
        f"<tr><td>{_esc(k)}</td><td>{_esc(v)}</td></tr>"
        for k, v in rows_data
    )
    return f"""
<div class="card">
  <h2>Solver Statistics</h2>
  <table>
    <thead><tr><th>Metric</th><th>Value</th></tr></thead>
    <tbody>{rows}</tbody>
  </table>
</div>
"""


# ---------------------------------------------------------------------------
# Plotly chart builders
# ---------------------------------------------------------------------------

def _build_gantt_figure(data: dict[str, Any], agents_sorted: list[str]) -> object:
    """Return a plotly Figure for the Gantt chart."""
    _require_plotly()
    import plotly.graph_objects as go

    assignments = data.get("assignments", [])
    critical_set = set(data.get("critical_path", []))
    agent_summary = data.get("agent_summary", [])

    # Look up price from original agents list (if solver carried it through)
    agents_raw = data.get("agents", [])
    price_map: dict[str, float] = {
        a["id"]: float(a.get("price_per_1k_tokens", 0.0))
        for a in agents_raw
        if isinstance(a, dict)
    }
    price_by_agent: dict[str, float] = {
        s["agent_id"]: price_map.get(s["agent_id"], 0.0)
        for s in agent_summary
    }

    row_map = {ag: i for i, ag in enumerate(agents_sorted)}
    traces = []
    for a in assignments:
        agent_id = a["agent_id"]
        is_crit = a["task_id"] in critical_set
        color = _color_for_agent(agent_id, agents_sorted)
        tokens = a.get("tokens", 0)
        price = price_by_agent.get(agent_id, 0.0)
        cost_str = f"${cost_dollars(tokens, price):.4f}" if price > 0 else "n/a"
        files_str = ", ".join(a.get("file_paths", []))
        hover = (
            f"<b>{a['task_id']}</b><br>"
            f"Agent: {agent_id}<br>"
            f"Duration: {a['duration']}<br>"
            f"t: {a['start']} &rarr; {a['end']}<br>"
            f"Tokens: {tokens:,}<br>"
            f"Files: {files_str or 'none'}<br>"
            f"Critical: {'yes' if is_crit else 'no'}<br>"
            f"Cost: {cost_str}"
        )
        marker: dict[str, Any] = {
            "color": color,
            "line": {
                "color": _CRITICAL_BORDER_COLOR if is_crit else "#333333",
                "width": 3 if is_crit else 0.5,
            },
        }
        if is_crit:
            marker["pattern"] = {"shape": _CRITICAL_MARKER_PATTERN, "fgcolor": "#ffffff"}

        traces.append(go.Bar(
            x=[a["end"] - a["start"]],
            y=[row_map.get(agent_id, 0)],
            base=[a["start"]],
            orientation="h",
            name=a["task_id"],
            text=[a["task_id"]],
            textposition="inside",
            insidetextanchor="middle",
            hovertemplate=hover + "<extra></extra>",
            marker=marker,
            showlegend=False,
            width=_GANTT_BAR_WIDTH,
        ))

    fig = go.Figure(data=traces)
    fig.update_layout(
        title="Interactive Gantt Chart",
        xaxis_title="Time units",
        yaxis={
            "tickvals": list(range(len(agents_sorted))),
            "ticktext": agents_sorted,
            "autorange": "reversed",
        },
        barmode="overlay",
        height=max(
            _GANTT_MIN_HEIGHT,
            len(agents_sorted) * _GANTT_PER_AGENT_HEIGHT + _GANTT_TITLE_PAD,
        ),
        template="plotly_white",
        margin={
            "l": _GANTT_MARGIN_L,
            "r": _GANTT_MARGIN_R,
            "t": _GANTT_MARGIN_T,
            "b": _GANTT_MARGIN_B,
        },
        legend_title="Legend",
    )
    # Legend items for agents
    for _i, ag in enumerate(agents_sorted):
        color = _color_for_agent(ag, agents_sorted)
        fig.add_trace(go.Bar(
            x=[0], y=[0], base=[0],
            orientation="h",
            name=ag,
            marker={"color": color},
            showlegend=True,
            visible="legendonly",
            hoverinfo="skip",
        ))
    return fig


def _hierarchical_positions(
    nodes: list[str],
    edges_all: list[tuple[str, str]],
) -> dict[str, tuple[float, float]]:
    """Assign (x, y) positions using topological depth (x) and spread (y)."""
    adj: dict[str, list[str]] = {n: [] for n in nodes}
    in_deg: dict[str, int] = dict.fromkeys(nodes, 0)
    for src, dst in edges_all:
        if src in adj and dst in in_deg:
            adj[src].append(dst)
            in_deg[dst] += 1

    # Kahn topological sort + layer assignment (longest path to node)
    depth: dict[str, int] = dict.fromkeys(nodes, 0)
    queue = sorted(n for n, d in in_deg.items() if d == 0)
    topo: list[str] = []
    temp_deg = dict(in_deg)
    while queue:
        node = queue.pop(0)
        topo.append(node)
        for nxt in sorted(adj[node]):
            depth[nxt] = max(depth[nxt], depth[node] + 1)
            temp_deg[nxt] -= 1
            if temp_deg[nxt] == 0:
                queue.append(nxt)

    # Group by depth, spread vertically
    by_depth: dict[int, list[str]] = defaultdict(list)
    for n in topo:
        by_depth[depth[n]].append(n)
    for remaining in nodes:
        if remaining not in depth:
            by_depth[0].append(remaining)

    pos: dict[str, tuple[float, float]] = {}
    for x_val, col_nodes in sorted(by_depth.items()):
        for y_idx, node in enumerate(sorted(col_nodes)):
            pos[node] = (float(x_val), float(y_idx))
    return pos


def _build_dag_figure(data: dict[str, Any], agents_sorted: list[str]) -> object:
    """Return a plotly Figure for the dependency DAG."""
    _require_plotly()
    import plotly.graph_objects as go

    assignments = data.get("assignments", [])
    parser_edges = [(e[0], e[1]) for e in data.get("edges", [])]
    resource_edges = [(e[0], e[1]) for e in data.get("resource_edges", [])]
    critical_path = data.get("critical_path", [])
    critical_set = set(critical_path)
    cp_edges_raw = data.get("critical_path_edges", list(pairwise(critical_path)))
    critical_edges = [(e[0], e[1]) for e in cp_edges_raw]

    nodes = [a["task_id"] for a in assignments]
    agent_of: dict[str, str] = {a["task_id"]: a["agent_id"] for a in assignments}

    all_edges_for_layout: list[tuple[str, str]] = list({
        *parser_edges, *resource_edges, *critical_edges,
    })
    pos = _hierarchical_positions(nodes, all_edges_for_layout)

    # Scale positions for better spacing
    max_x = max((xy[0] for xy in pos.values()), default=1)
    max_y = max((xy[1] for xy in pos.values()), default=1)
    x_scale = 2.0 if max_x == 0 else 10.0 / max(max_x, 1)
    y_scale = 2.0 if max_y == 0 else 6.0 / max(max_y, 1)

    scaled_pos: dict[str, tuple[float, float]] = {
        n: (xy[0] * x_scale, xy[1] * y_scale) for n, xy in pos.items()
    }

    def _make_edge_trace(
        edges: list[tuple[str, str]],
        color: str,
        dash: str,
        width: float,
        name: str,
    ) -> object:
        ex: list[float | None] = []
        ey: list[float | None] = []
        for src, dst in edges:
            if src not in scaled_pos or dst not in scaled_pos:
                continue
            sx, sy = scaled_pos[src]
            dx, dy = scaled_pos[dst]
            ex += [sx, dx, None]
            ey += [sy, dy, None]
        return go.Scatter(
            x=ex, y=ey,
            mode="lines",
            line={"color": color, "dash": dash, "width": width},
            name=name,
            hoverinfo="skip",
        )

    traces: list[object] = []
    drawn_crit = set(critical_edges)
    non_crit_parser = [e for e in parser_edges if e not in drawn_crit]
    non_crit_resource = [e for e in resource_edges if e not in drawn_crit]

    if non_crit_parser:
        traces.append(_make_edge_trace(
            non_crit_parser, _PARSER_EDGE_COLOR, "solid", 1.0, "Parser edges",
        ))
    if non_crit_resource:
        traces.append(_make_edge_trace(
            non_crit_resource, _RESOURCE_EDGE_COLOR, "dash", 1.0, "Resource edges",
        ))
    if critical_edges:
        traces.append(_make_edge_trace(
            critical_edges, _CRITICAL_EDGE_COLOR, "solid", 3.0, "Critical path",
        ))

    # Node trace (one per agent colour for legend)
    agent_to_nodes: dict[str, list[str]] = defaultdict(list)
    for node in nodes:
        agent_to_nodes[agent_of.get(node, "")].append(node)

    for agent_id in agents_sorted:
        color = _color_for_agent(agent_id, agents_sorted)
        agent_nodes = agent_to_nodes.get(agent_id, [])
        if not agent_nodes:
            continue
        nx_coords = [scaled_pos[n][0] for n in agent_nodes if n in scaled_pos]
        ny_coords = [scaled_pos[n][1] for n in agent_nodes if n in scaled_pos]
        is_crit = [n in critical_set for n in agent_nodes if n in scaled_pos]
        valid_nodes = [n for n in agent_nodes if n in scaled_pos]
        sizes = [18 if c else 12 for c in is_crit]
        borders = [_CRITICAL_BORDER_COLOR if c else "#333333" for c in is_crit]
        border_widths = [3 if c else 1 for c in is_crit]
        hovers = [
            f"<b>{n}</b><br>Agent: {agent_id}<br>Critical: {'yes' if c else 'no'}"
            for n, c in zip(valid_nodes, is_crit, strict=True)
        ]
        traces.append(go.Scatter(
            x=nx_coords, y=ny_coords,
            mode="markers+text",
            name=agent_id,
            text=valid_nodes,
            textposition="top center",
            textfont={"size": 9},
            hovertemplate=[h + "<extra></extra>" for h in hovers],
            marker={
                "color": color,
                "size": sizes,
                "line": {"color": borders, "width": border_widths},
            },
        ))

    height = max(400, len(nodes) * 8 + 200)
    fig = go.Figure(data=traces)
    fig.update_layout(
        title="Interactive Dependency DAG",
        xaxis={"visible": False},
        yaxis={"visible": False},
        height=height,
        template="plotly_white",
        margin={"l": 20, "r": 20, "t": 60, "b": 20},
        legend_title="Legend",
    )
    return fig


# ---------------------------------------------------------------------------
# Main render function
# ---------------------------------------------------------------------------

def render(
    data: dict[str, Any],
    feature_name: str,
    *,
    inline_plotly: bool = False,
) -> str:
    """Render solver output as a self-contained HTML string.

    Parameters
    ----------
    data:
        Solver output dict. The expected shape is
        :class:`solver.model.result_types.ScheduleResult` — every key the
        renderer reads is documented there. The annotation stays as
        ``dict[str, Any]`` because mypy's TypedDict variance rules block
        passing a ``ScheduleResult`` value to helpers expecting
        ``dict[str, Any]``; treat ``ScheduleResult`` as the schema doc.
    feature_name:
        Human-readable feature name shown in the header.
    inline_plotly:
        When True, embed the full plotly.js bundle (~4 MB) so the file
        works fully offline. When False (default), load from CDN.
    """
    _require_plotly()
    import plotly.io as pio

    assignments = data.get("assignments", [])
    agents_sorted, _color_by_agent = palette_for(assignments)

    # Build HTML sections
    header = _header_html(data, feature_name)
    warnings = _warnings_html(data)
    agent_html = _agent_assignments_html(data, agents_sorted)
    waves = _waves_html(data)
    cp_html = _critical_path_html(data)
    stats = _stats_html(data)

    # Build Plotly figures
    gantt_fig = _build_gantt_figure(data, agents_sorted)
    dag_fig = _build_dag_figure(data, agents_sorted)

    include_plotlyjs: str | bool = "cdn" if not inline_plotly else True
    gantt_html = pio.to_html(
        gantt_fig,
        full_html=False,
        include_plotlyjs=include_plotlyjs,
        div_id="gantt-chart",
    )
    # Second chart: always pass include_plotlyjs=False so it reuses the
    # already-loaded plotly from the Gantt (whether CDN or inline).
    dag_html = pio.to_html(
        dag_fig,
        full_html=False,
        include_plotlyjs=False,
        div_id="dag-chart",
    )

    css = """
<style>
  :root {
    --bg: #f8f9fa;
    --card-bg: #ffffff;
    --border: #dee2e6;
    --text: #212529;
    --accent: #4A90D9;
  }
  body { font-family: system-ui, sans-serif; background: var(--bg);
         color: var(--text); margin: 0; padding: 1rem 2rem; }
  h1 { margin-top: 0; color: var(--accent); }
  h2 { border-bottom: 2px solid var(--border); padding-bottom: 0.3rem; }
  .card { background: var(--card-bg); border: 1px solid var(--border);
          border-radius: 8px; padding: 1.2rem 1.5rem; margin-bottom: 1.5rem; }
  .header-card { border-left: 6px solid var(--accent); }
  .warnings-card { border-left: 6px solid #f39c12; background: #fffbf0; }
  .badges { display: flex; flex-wrap: wrap; gap: 0.5rem; margin-top: 0.5rem; }
  .badge { background: #4A90D9; color: #fff; border-radius: 4px;
           padding: 0.25rem 0.6rem; font-size: 0.85rem; }
  .agent-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(300px,1fr));
                gap: 1rem; }
  .agent-card { background: #f9f9f9; border-radius: 6px; padding: 0.8rem 1rem; }
  .agent-card h3 { margin-top: 0; }
  .agent-card ul { padding-left: 1.2rem; font-size: 0.85rem; }
  details > summary { cursor: pointer; font-weight: 600; padding: 0.4rem 0;
                      list-style: disclosure-closed; }
  details[open] > summary { list-style: disclosure-open; }
  table { border-collapse: collapse; width: 100%; font-size: 0.875rem; }
  th { background: #f1f3f5; text-align: left; padding: 0.4rem 0.6rem;
       border-bottom: 2px solid var(--border); }
  td { padding: 0.35rem 0.6rem; border-bottom: 1px solid #e9ecef; }
  tr:last-child td { border-bottom: none; }
  code { background: #e9ecef; border-radius: 3px; padding: 0.1em 0.3em;
         font-size: 0.85em; }
  .chart-section { margin-top: 1rem; }
</style>
"""

    body = "\n".join([
        header,
        warnings,
        agent_html,
        waves,
        cp_html,
        f'<div class="card chart-section"><h2>Gantt Chart</h2>{gantt_html}</div>',
        f'<div class="card chart-section"><h2>Dependency DAG</h2>{dag_html}</div>',
        stats,
    ])

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Schedule &mdash; {_esc(feature_name)}</title>
  {css}
</head>
<body>
{body}
</body>
</html>"""


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _build_argparser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(
        prog="render_html.py",
        description="Render solver output JSON into a self-contained schedule.html.",
    )
    ap.add_argument("input", help="Path to solver output JSON")
    ap.add_argument("feature_name")
    ap.add_argument(
        "--inline-plotly",
        action="store_true",
        default=False,
        help="Embed full plotly.js bundle (~4 MB) for fully offline output.",
    )
    return ap


def main(argv: list[str] | None = None) -> int:
    args = _build_argparser().parse_args(argv)
    with open(args.input, encoding="utf-8") as f:
        data = json.load(f)
    try:
        html_out = render(
            data,
            args.feature_name,
            inline_plotly=args.inline_plotly,
        )
    except ImportError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2
    sys.stdout.write(html_out)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
